### ISSUE TITLE
Only firing on window resize

### ISSUE THREAD

**Issue by nitrokevin** [midnightviking/textsive#1]
Hi just stumbled across this and its exactly what I'm looking for, I'm using it on a website built with foundation but its only working if you resize the window, not when the page first loads any ideas why?

**Comment by midnightviking** [comment]
Hi! Do you anywhere I can see the site in question? Or a snippet of you javascript that might be preventing the initialization from firing? 

Off the top of my head all I can think is that either the .textsive() function isnt calling after the elements have loaded, or theres something preventing the initial fire. I'd be happy to take a look if you have it somewhere online I can view it. 

Thanks! Hope I can help you resolve this,
Mike
